### ISSUE TITLE
handle null image in StackedImageColumn

### ISSUE THREAD

**Issue by fullyloadedtech** [archilex/filament-stacked-image-column#4]
Could use a way to set a default image or allow null image for relations which do not have an image set. Unless you make your related model image required, wind up getting an error when trying to view StackedImageColumn in a table with any missing images.

**Comment by archilex** [comment]
defaultImageUrl is already a part of the v3 stackedImageColumn so I'll try to backport that in the coming weeks. Slammed with work right now, but I'll get to it eventually. Thanks!

**Comment by dogeow** [comment]
@archilex Is there a way to click on the thumb to enlarge the picture? Thank you.

**Comment by archilex** [comment]
> @archilex Is there a way to click on the thumb to enlarge the picture? Thank you.

This functionality doesn't exist currently, but I might look into it at a later date.
